backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Data"
    name: "data"
    files:
      - label: "Matches"
        name: "matches"
        file: "content/matches.json"
        fields:
          - label: Matches
            name: matches
            widget: list
            fields:
              - { label: Slug, name: slug, widget: string }
              - { label: Start time, name: start_time, widget: string }
              - label: "Group"
                name: "group"
                widget: "select"
                options: ["A", "B", "C", "D"]
              - label: "Number of games"
                name: "number_of_games"
                widget: "select"
                options: ["1", "5"]
              - label: "Match status"
                name: "status"
                widget: "select"
                options: ["NOT_STARTED", "INPLAY", "FINISHED"]
              - label: Participants
                name: participants
                widget: list
                fields:
                  - { label: Participant name, name: name, widget: string }
                  - { label: Participant logo, name: logo, widget: string }
                  - { label: Participant score, name: score, widget: string }
                  - {
                      label: Participant winning,
                      name: winning,
                      widget: boolean,
                      required: false,
                      default: false,
                    }
              - {
                  label: Must see,
                  name: must_see,
                  widget: boolean,
                  required: false,
                  default: false,
                }
              - {
                  label: Gold,
                  name: gold,
                  widget: boolean,
                  required: false,
                  default: false,
                }
              - label: VODS
                name: vods
                widget: list
                fields:
                  - { label: Game link, name: link, widget: string }
