backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "Contacts"
        name: "contacts"
        file: "content/contacts.json"
        fields:
          - label: "Avatar"
            name: "src"
            widget: "image"
          - { label: Full Name, name: full_name, widget: string }
          - { label: Position, name: position, widget: string }
          - { label: Tel, name: tel, widget: string }
          - { label: Second Tel, name: second_tel, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Adress, name: adress, widget: string }
