backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "Upcoming matches"
        name: "upcoming_matches"
        file: "content/upcoming_matches.json"
        fields:
          - { label: Start time, name: start_time, widget: string }
          - {
              label: Participant first,
              name: participant_first,
              widget: string,
            }
          - { label: Tel, name: tel, widget: string }
          - { label: Second Tel, name: second_tel, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Adress, name: adress, widget: string }
